const TRANSLATIONS = {
  en: {
    'nav-practice':'Practice','nav-courses':'Courses','nav-join-free':'Join Free',
    'nav-login':'Log In','nav-logout':'Log Out','nav-badges':'Badges',
    'nav-support':'Support','nav-about':'About','nav-privacy':'Privacy Policy','nav-terms':'Terms of Service',
    'hero-sub':'Reclaim Your Ageless Body',
    'hero-badge':'Trusted by <strong>3,400+</strong> practitioners in 40+ countries',
    'hero-btn':'Start Free Today',
    'stat-members':'Members Worldwide','stat-countries':'Countries',
    'stat-rating':'Average Rating','stat-years':'Years of Teaching',
    'why-title-1':'Just 15 minutes a day','why-sub-1':'All you need to start reversing aging',
    'why-title-2':'Completely from home','why-sub-2':'No gym, no commute, no schedule',
    'why-title-3':'Zero equipment needed','why-sub-3':'Just your body and 21 years of guidance',
    'section4-title':'Minutes a Day. Years Returned.',
    'section4-body':'Access your full library of guided sessions from any device — from 10-minute morning rituals to complete hour-long practices. Every session is built around the same five core movements that speak directly to your spine, your energy centers, and your hormonal system. The result: you start moving, feeling, and looking younger — naturally, without drugs, without surgery, and without leaving home.',
    'testi-heading':'Real Results From Real People',
    'testi-sub':'Over <strong style="color:#1e3a8a">3,400 members</strong> across 40+ countries have reclaimed their youth. Here\'s what a few are saying.',
    'cta-community':'Join <strong style="color:#1e3a8a">3,400+ members</strong> who are already living younger.',
    'cta-btn':'Start Free — No Credit Card Needed',
    'cta-sub':'Free to start &nbsp;·&nbsp; 15 minutes a day &nbsp;·&nbsp; Cancel anytime',
    'modal-title':'Join 3,400+ Members Worldwide',
    'modal-stars':'★★★★★ &ensp;Start free today — no credit card needed',
    'modal-b1-title':'Ancient Wisdom. Modern Results.',
    'modal-b1-sub':"Five daily movements that reactivate your body's natural youth mechanisms",
    'modal-b2-title':'Reverse Physical Aging',
    'modal-b2-sub':'Restore energy, mobility, and vitality — from the very first session',
    'modal-b3-title':'Practice Anywhere, Anytime',
    'modal-b3-sub':'Your complete anti-aging movement library, on any device',
    'modal-fname':'First name','modal-fname-ph':'first name',
    'modal-email':'Email','modal-email-ph':'email address',
    'modal-signup-btn':'Sign Up',
    'modal-legal':'By joining you agree to our','modal-have-account':'Already have an account?',
    'page-practice':'Practice',
    'page-practice-sub':"Ancient movement practices to restore vitality, mobility, and your body's natural youth.",
    'sec-classes':'Classes','sec-series':'Series','btn-viewall':'View all',
    'label-members-only':'Members Only','label-free':'FREE',
    'modal-unlock-title':'Unlock Full Access','modal-unlock-sub':'All classes, all series — unlimited.',
    'plan-annual':'Annual','plan-annual-sub':'Less than €8 / month',
    'plan-best-value':'Best Value','plan-annual-cycle':'per year',
    'plan-monthly':'Monthly','plan-monthly-sub':'Cancel anytime','plan-monthly-cycle':'per month',
    'btn-get-access':'Get Full Access','modal-tiny':'Immediate access. Cancel anytime.',
    'page-courses':'Courses',
    'page-courses-sub':'Intensive programs built on ancient movement science — designed to return your body to its most vital, capable self.',
    'btn-view-course':'View Course',
    'pay-subscribe':'Subscribe to Yogi Khasha','pay-one-time':'One-time Purchase',
    'pay-instant':'Instant access · No subscription required',
    'pay-lifetime':'Lifetime access · No subscription required',
    'pay-billed-yearly':'Billed yearly · Cancel anytime',
    'pay-billed-monthly':'Billed monthly · Cancel anytime',
    'pay-subtotal':'Subtotal','pay-after-trial':'Total after trial','pay-due-today':'Due today',
    'pay-promo-ph':'Add promotion code','pay-apply':'Apply',
    'pay-express':'Express Checkout','pay-or-card':'or pay with card',
    'pay-email':'Email','pay-payment-details':'Payment Details',
    'pay-card-number':'Card Number','pay-expiry':'Expiry','pay-cvc':'CVC',
    'pay-cardholder':'Cardholder Name','pay-country':'Country',
    'pay-save':'Save payment details for future purchases',
    'pay-btn-subscribe':'Subscribe now',
    'page-badges':'Badges','page-badges-sub':'Each milestone etched into your body.',
    'badge-tier-initiate':'Initiate','badge-tier-practitioner':'Practitioner',
    'badge-tier-warrior':'Warrior','badge-tier-master':'Master',
    'badge-days':'days','badge-locked':'Locked',
    'footer-copy':'© 2026 Yogi Khasha · All content © Multi Yoga Style · All rights reserved.',
    'footer-support':'Support','footer-privacy':'Privacy Policy','footer-terms':'Terms of Service',
    'btn-buy-now':'Buy Now','lbl-instant-access':'Instant access · No subscription required',
    'lbl-course-content':'Course Content','lbl-online-course':'Online Course',
    'lbl-by':'By'
  },
  de: {
    'nav-practice':'Praxis','nav-courses':'Kurse','nav-join-free':'Kostenlos starten',
    'nav-login':'Anmelden','nav-logout':'Abmelden','nav-badges':'Abzeichen',
    'nav-support':'Support','nav-about':'Über uns','nav-privacy':'Datenschutz','nav-terms':'Nutzungsbedingungen',
    'hero-sub':'Fordere Deinen Zeitlosen Körper Zurück',
    'hero-badge':'Vertraut von über <strong>3.400</strong> Praktizierenden in 40+ Ländern',
    'hero-btn':'Kostenlos starten',
    'stat-members':'Weltweite Mitglieder','stat-countries':'Länder',
    'stat-rating':'Durchschnittsbewertung','stat-years':'Jahre Erfahrung',
    'why-title-1':'Nur 15 Minuten am Tag','why-sub-1':'Alles, was du brauchst, um das Altern umzukehren',
    'why-title-2':'Komplett von zu Hause','why-sub-2':'Kein Studio, kein Pendelweg, kein Zeitplan',
    'why-title-3':'Kein Equipment nötig','why-sub-3':'Nur dein Körper und 21 Jahre Erfahrung',
    'section4-title':'Minuten am Tag. Jahre zurückgewonnen.',
    'section4-body':'Greife von jedem Gerät auf deine gesamte Bibliothek geführter Einheiten zu — von 10-minütigen Morgenritualen bis hin zu vollständigen einstündigen Praktiken. Jede Einheit basiert auf denselben fünf Kernbewegungen, die direkt auf deine Wirbelsäule, deine Energiezentren und dein Hormonsystem wirken. Das Ergebnis: Du beginnst dich jünger zu bewegen, zu fühlen und auszusehen — auf natürliche Weise, ohne Medikamente, ohne Chirurgie und ohne das Haus zu verlassen.',
    'testi-heading':'Echte Ergebnisse von echten Menschen',
    'testi-sub':'Über <strong style="color:#1e3a8a">3.400 Mitglieder</strong> in mehr als 40 Ländern haben ihre Jugend zurückerobert.',
    'cta-community':'Schließe dich <strong style="color:#1e3a8a">über 3.400 Mitgliedern</strong> an, die bereits jünger leben.',
    'cta-btn':'Kostenlos starten — Keine Kreditkarte nötig',
    'cta-sub':'Kostenlos starten &nbsp;·&nbsp; 15 Minuten am Tag &nbsp;·&nbsp; Jederzeit kündbar',
    'modal-title':'Werde Teil von über 3.400 Mitgliedern',
    'modal-stars':'★★★★★ &ensp;Kostenlos starten — keine Kreditkarte nötig',
    'modal-b1-title':'Altes Wissen. Moderne Ergebnisse.',
    'modal-b1-sub':'Fünf tägliche Bewegungen, die die natürlichen Verjüngungsmechanismen deines Körpers reaktivieren',
    'modal-b2-title':'Körperliches Altern umkehren',
    'modal-b2-sub':'Energie, Mobilität und Vitalität wiederherstellen — ab der ersten Einheit',
    'modal-b3-title':'Überall und jederzeit üben',
    'modal-b3-sub':'Deine vollständige Anti-Aging-Bewegungsbibliothek auf jedem Gerät',
    'modal-fname':'Vorname','modal-fname-ph':'Vorname',
    'modal-email':'E-Mail','modal-email-ph':'E-Mail-Adresse',
    'modal-signup-btn':'Konto erstellen',
    'modal-legal':'Mit deiner Anmeldung stimmst du unseren zu','modal-have-account':'Bereits ein Konto?',
    'page-practice':'Praxis',
    'page-practice-sub':'Alte Bewegungspraktiken zur Wiederherstellung von Vitalität, Mobilität und natürlicher Jugendlichkeit.',
    'sec-classes':'Klassen','sec-series':'Serien','btn-viewall':'Alle anzeigen',
    'label-members-only':'Nur Mitglieder','label-free':'KOSTENLOS',
    'modal-unlock-title':'Vollen Zugang freischalten','modal-unlock-sub':'Alle Klassen, alle Serien — unbegrenzt.',
    'plan-annual':'Jährlich','plan-annual-sub':'Weniger als €8 / Monat',
    'plan-best-value':'Bestes Angebot','plan-annual-cycle':'pro Jahr',
    'plan-monthly':'Monatlich','plan-monthly-sub':'Jederzeit kündbar','plan-monthly-cycle':'pro Monat',
    'btn-get-access':'Vollen Zugang erhalten','modal-tiny':'Sofortiger Zugang. Jederzeit kündbar.',
    'page-courses':'Kurse',
    'page-courses-sub':'Intensive Programme auf Basis alter Bewegungswissenschaft — entwickelt, um deinen Körper zu seiner vitalsten Form zurückzubringen.',
    'btn-view-course':'Kurs ansehen',
    'pay-subscribe':'Yogi Khasha abonnieren','pay-one-time':'Einmaliger Kauf',
    'pay-instant':'Sofortiger Zugang · Kein Abonnement erforderlich',
    'pay-lifetime':'Lebenslanger Zugang · Kein Abonnement erforderlich',
    'pay-billed-yearly':'Jährliche Abrechnung · Jederzeit kündbar',
    'pay-billed-monthly':'Monatliche Abrechnung · Jederzeit kündbar',
    'pay-subtotal':'Zwischensumme','pay-after-trial':'Gesamtbetrag nach Test','pay-due-today':'Heute fällig',
    'pay-promo-ph':'Aktionscode hinzufügen','pay-apply':'Anwenden',
    'pay-express':'Expressbestellung','pay-or-card':'oder mit Karte bezahlen',
    'pay-email':'E-Mail','pay-payment-details':'Zahlungsdetails',
    'pay-card-number':'Kartennummer','pay-expiry':'Ablaufdatum','pay-cvc':'CVC',
    'pay-cardholder':'Karteninhaber','pay-country':'Land',
    'pay-save':'Zahlungsdaten für zukünftige Käufe speichern',
    'pay-btn-subscribe':'Jetzt abonnieren',
    'page-badges':'Abzeichen','page-badges-sub':'Jeder Meilenstein in deinen Körper eingraviert.',
    'badge-tier-initiate':'Anfänger','badge-tier-practitioner':'Praktizierender',
    'badge-tier-warrior':'Krieger','badge-tier-master':'Meister',
    'badge-days':'Tage','badge-locked':'Gesperrt',
    'footer-copy':'© 2026 Yogi Khasha · Alle Inhalte © Multi Yoga Style · Alle Rechte vorbehalten.',
    'footer-support':'Support','footer-privacy':'Datenschutzrichtlinie','footer-terms':'Nutzungsbedingungen',
    'btn-buy-now':'Jetzt kaufen','lbl-instant-access':'Sofortiger Zugang · Kein Abonnement',
    'lbl-course-content':'Kursinhalt','lbl-online-course':'Online-Kurs',
    'lbl-by':'Von'
  },
  es: {
    'nav-practice':'Práctica','nav-courses':'Cursos','nav-join-free':'Empieza Gratis',
    'nav-login':'Iniciar Sesión','nav-logout':'Cerrar Sesión','nav-badges':'Insignias',
    'nav-support':'Soporte','nav-about':'Acerca de','nav-privacy':'Política de Privacidad','nav-terms':'Términos de Servicio',
    'hero-sub':'Reclama Tu Cuerpo Sin Edad',
    'hero-badge':'De confianza para más de <strong>3.400</strong> practicantes en más de 40 países',
    'hero-btn':'Empieza Gratis Hoy',
    'stat-members':'Miembros en el Mundo','stat-countries':'Países',
    'stat-rating':'Valoración Media','stat-years':'Años de Enseñanza',
    'why-title-1':'Solo 15 minutos al día','why-sub-1':'Todo lo que necesitas para revertir el envejecimiento',
    'why-title-2':'Completamente desde casa','why-sub-2':'Sin gimnasio, sin desplazamientos, sin horarios',
    'why-title-3':'Sin equipamiento necesario','why-sub-3':'Solo tu cuerpo y 21 años de guía',
    'section4-title':'Minutos al Día. Años Devueltos.',
    'section4-body':'Accede a tu biblioteca completa de sesiones guiadas desde cualquier dispositivo — desde rituales matutinos de 10 minutos hasta prácticas completas de una hora. Cada sesión está construida alrededor de los mismos cinco movimientos centrales que hablan directamente a tu columna, tus centros de energía y tu sistema hormonal. El resultado: empiezas a moverte, sentirte y verte más joven — de forma natural, sin medicamentos, sin cirugía y sin salir de casa.',
    'testi-heading':'Resultados Reales de Personas Reales',
    'testi-sub':'Más de <strong style="color:#1e3a8a">3.400 miembros</strong> en más de 40 países han recuperado su juventud.',
    'cta-community':'Únete a <strong style="color:#1e3a8a">más de 3.400 miembros</strong> que ya están viviendo más jóvenes.',
    'cta-btn':'Empieza Gratis — Sin Tarjeta de Crédito',
    'cta-sub':'Gratis para empezar &nbsp;·&nbsp; 15 minutos al día &nbsp;·&nbsp; Cancela cuando quieras',
    'modal-title':'Únete a Más de 3.400 Miembros',
    'modal-stars':'★★★★★ &ensp;Empieza gratis hoy — sin tarjeta de crédito',
    'modal-b1-title':'Sabiduría Ancestral. Resultados Modernos.',
    'modal-b1-sub':'Cinco movimientos diarios que reactivan los mecanismos de juventud natural de tu cuerpo',
    'modal-b2-title':'Revertir el Envejecimiento Físico',
    'modal-b2-sub':'Restaura energía, movilidad y vitalidad — desde la primera sesión',
    'modal-b3-title':'Practica en Cualquier Lugar',
    'modal-b3-sub':'Tu biblioteca completa de movimiento anti-envejecimiento, en cualquier dispositivo',
    'modal-fname':'Nombre','modal-fname-ph':'nombre',
    'modal-email':'Correo electrónico','modal-email-ph':'dirección de correo',
    'modal-signup-btn':'Crear Cuenta',
    'modal-legal':'Al unirte aceptas nuestros','modal-have-account':'¿Ya tienes una cuenta?',
    'page-practice':'Práctica',
    'page-practice-sub':'Prácticas de movimiento ancestral para restaurar la vitalidad, la movilidad y la juventud natural de tu cuerpo.',
    'sec-classes':'Clases','sec-series':'Series','btn-viewall':'Ver todo',
    'label-members-only':'Solo Miembros','label-free':'GRATIS',
    'modal-unlock-title':'Desbloquea el Acceso Completo','modal-unlock-sub':'Todas las clases, todas las series — ilimitado.',
    'plan-annual':'Anual','plan-annual-sub':'Menos de €8 / mes',
    'plan-best-value':'Mejor Precio','plan-annual-cycle':'por año',
    'plan-monthly':'Mensual','plan-monthly-sub':'Cancela cuando quieras','plan-monthly-cycle':'por mes',
    'btn-get-access':'Obtener Acceso Completo','modal-tiny':'Acceso inmediato. Cancela cuando quieras.',
    'page-courses':'Cursos',
    'page-courses-sub':'Programas intensivos basados en ciencia del movimiento ancestral — diseñados para devolver a tu cuerpo su estado más vital.',
    'btn-view-course':'Ver Curso',
    'pay-subscribe':'Suscríbete a Yogi Khasha','pay-one-time':'Compra Única',
    'pay-instant':'Acceso inmediato · Sin suscripción necesaria',
    'pay-lifetime':'Acceso de por vida · Sin suscripción necesaria',
    'pay-billed-yearly':'Facturación anual · Cancela cuando quieras',
    'pay-billed-monthly':'Facturación mensual · Cancela cuando quieras',
    'pay-subtotal':'Subtotal','pay-after-trial':'Total tras el periodo de prueba','pay-due-today':'Total hoy',
    'pay-promo-ph':'Añadir código promocional','pay-apply':'Aplicar',
    'pay-express':'Pago Rápido','pay-or-card':'o paga con tarjeta',
    'pay-email':'Correo electrónico','pay-payment-details':'Detalles de Pago',
    'pay-card-number':'Número de Tarjeta','pay-expiry':'Caducidad','pay-cvc':'CVC',
    'pay-cardholder':'Nombre del Titular','pay-country':'País',
    'pay-save':'Guardar datos de pago para futuras compras',
    'pay-btn-subscribe':'Suscribirse ahora',
    'page-badges':'Insignias','page-badges-sub':'Cada hito grabado en tu cuerpo.',
    'badge-tier-initiate':'Iniciado','badge-tier-practitioner':'Practicante',
    'badge-tier-warrior':'Guerrero','badge-tier-master':'Maestro',
    'badge-days':'días','badge-locked':'Bloqueado',
    'footer-copy':'© 2026 Yogi Khasha · Todo el contenido © Multi Yoga Style · Todos los derechos reservados.',
    'footer-support':'Soporte','footer-privacy':'Política de Privacidad','footer-terms':'Términos de Servicio',
    'btn-buy-now':'Comprar ahora','lbl-instant-access':'Acceso inmediato · Sin suscripción',
    'lbl-course-content':'Contenido del Curso','lbl-online-course':'Curso Online',
    'lbl-by':'Por'
  }
};

function getLang(){ return localStorage.getItem('yk_lang')||'en'; }
function setLang(l){ localStorage.setItem('yk_lang',l); applyLang(); }
function applyLang(){
  const t=TRANSLATIONS[getLang()]||TRANSLATIONS.en;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const k=el.getAttribute('data-i18n');
    if(t[k]!==undefined) el.innerHTML=t[k];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el=>{
    const k=el.getAttribute('data-i18n-ph');
    if(t[k]!==undefined) el.placeholder=t[k];
  });
  document.querySelectorAll('.lang-select').forEach(sel=>{ sel.value=getLang(); });
}
document.addEventListener('DOMContentLoaded',applyLang);
