const TRANSLATIONS = {
  en: {
    'nav-practice':'Practice','nav-courses':'Courses','nav-join-free':'Join Free',
    'nav-login':'Log In','nav-logout':'Log Out','nav-badges':'Badges',
    'nav-support':'Support','nav-about':'About','nav-privacy':'Privacy Policy','nav-terms':'Terms of Service',
    'hero-sub':'Reclaim Your Ageless Body',
    'hero-badge':'Trusted by <strong>3,400+</strong> practitioners in 40+ countries',
    'hero-btn':'Start Free Today',
    'stat-members':'Members Worldwide','stat-countries':'Countries',
    'stat-rating':'Average Rating','stat-years':'Years of Teaching',
    'why-title-1':'Just 15 minutes a day','why-sub-1':'All you need to start reversing aging',
    'why-title-2':'Completely from home','why-sub-2':'No gym, no commute, no schedule',
    'why-title-3':'Zero equipment needed','why-sub-3':'Just your body and 21 years of guidance',
    'section4-title':'Minutes a Day. Years Returned.',
    'section4-body':'Access your full library of guided sessions from any device — from 10-minute morning rituals to complete hour-long practices. Every session is built around the same five core movements that speak directly to your spine, your energy centers, and your hormonal system. The result: you start moving, feeling, and looking younger — naturally, without drugs, without surgery, and without leaving home.',
    'testi-heading':'Real Results From Real People',
    'testi-sub':'Over <strong style="color:#1e3a8a">3,400 members</strong> across 40+ countries have reclaimed their youth. Here\'s what a few are saying.',
    'cta-community':'Join <strong style="color:#1e3a8a">3,400+ members</strong> who are already living younger.',
    'cta-btn':'Start Free — No Credit Card Needed',
    'cta-sub':'Free to start &nbsp;·&nbsp; 15 minutes a day &nbsp;·&nbsp; Cancel anytime',
    'modal-title':'Join 3,400+ Members Worldwide',
    'modal-stars':'★★★★★ &ensp;Start free today — no credit card needed',
    'modal-b1-title':'Ancient Wisdom. Modern Results.',
    'modal-b1-sub':"Five daily movements that reactivate your body's natural youth mechanisms",
    'modal-b2-title':'Reverse Physical Aging',
    'modal-b2-sub':'Restore energy, mobility, and vitality — from the very first session',
    'modal-b3-title':'Practice Anywhere, Anytime',
    'modal-b3-sub':'Your complete anti-aging movement library, on any device',
    'modal-fname':'First name','modal-fname-ph':'first name',
    'modal-email':'Email','modal-email-ph':'email address',
    'modal-signup-btn':'Sign Up',
    'modal-legal':'By joining you agree to our','modal-have-account':'Already have an account?',
    'page-practice':'Practice',
    'page-practice-sub':"Ancient movement practices to restore vitality, mobility, and your body's natural youth.",
    'sec-classes':'Classes','sec-series':'Series','btn-viewall':'View all',
    'label-members-only':'Members Only','label-free':'FREE',
    'modal-unlock-title':'Unlock Full Access','modal-unlock-sub':'All classes, all series — unlimited.',
    'plan-annual':'Annual','plan-annual-sub':'Less than €8 / month',
    'plan-best-value':'Best Value','plan-annual-cycle':'per year',
    'plan-monthly':'Monthly','plan-monthly-sub':'Cancel anytime','plan-monthly-cycle':'per month',
    'btn-get-access':'Get Full Access','modal-tiny':'Immediate access. Cancel anytime.',
    'page-courses':'Courses',
    'page-courses-sub':'Intensive programs built on ancient movement science — designed to return your body to its most vital, capable self.',
    'btn-view-course':'View Course',
    'pay-subscribe':'Subscribe to Yogi Khasha','pay-one-time':'One-time Purchase',
    'pay-instant':'Instant access · No subscription required',
    'pay-lifetime':'Lifetime access · No subscription required',
    'pay-billed-yearly':'Billed yearly · Cancel anytime',
    'pay-billed-monthly':'Billed monthly · Cancel anytime',
    'pay-subtotal':'Subtotal','pay-after-trial':'Total after trial','pay-due-today':'Due today',
    'pay-promo-ph':'Add promotion code','pay-apply':'Apply',
    'pay-express':'Express Checkout','pay-or-card':'or pay with card',
    'pay-email':'Email','pay-payment-details':'Payment Details',
    'pay-card-number':'Card Number','pay-expiry':'Expiry','pay-cvc':'CVC',
    'pay-cardholder':'Cardholder Name','pay-country':'Country',
    'pay-save':'Save payment details for future purchases',
    'pay-btn-subscribe':'Subscribe now',
    'page-badges':'Badges','page-badges-sub':'Each milestone etched into your body.',
    'badge-tier-initiate':'Initiate','badge-tier-practitioner':'Practitioner',
    'badge-tier-warrior':'Warrior','badge-tier-master':'Master',
    'badge-days':'days','badge-locked':'Locked',
    'footer-copy':'© 2026 Yogi Khasha · All content © Multi Yoga Style · All rights reserved.',
    'footer-support':'Support','footer-privacy':'Privacy Policy','footer-terms':'Terms of Service',
    'btn-buy-now':'Buy Now','lbl-instant-access':'Instant access · No subscription required',
    'lbl-course-content':'Course Content','lbl-online-course':'Online Course',
    'lbl-by':'By',
    'section-h1-main':"The Ancient 5-Movement Daily Practice That Turns Back Your Body's Clock — More Energy, Less Pain, And A Spine That Feels 20 Years Younger.",
    'about-body':"With over 21 years of teaching experience and thousands of transformed lives, Yogi Khasha has spent two decades mastering the ancient movement sequences that modern science now confirms: five specific movements, practiced daily, that reactivate your body's natural youth mechanisms. This isn't exercise — it's the most powerful anti-aging ritual your body was designed to perform.",
    'quote-text':"''I genuinely did not believe a daily movement practice could change this much. Within three weeks I had lost the stiffness I'd carried for years, my energy was back, and people kept asking if I'd done something different. The answer was just this — five movements, every morning. That's it.''",
    'footer-tagline':'Made with ♥ on planet earth.',
    'testi-1-txt':"I spent years believing stiffness and low energy were just part of getting older. After six weeks with Yogi Khasha, my mornings are completely different — I wake up with real energy, my back doesn't ache, and I move like I did in my forties. I'm 61.",
    'testi-2-txt':"I almost didn't notice the change until my daughter said, 'Mum, you're walking differently.' Taller. More confident. Three months in, I haven't missed a single day.",
    'testi-3-txt':"I was a skeptic — energy centers and ancient rituals are not usually my language. But the results are undeniable. Less pain, more energy, better sleep, and a posture my physiotherapist actually commented on. Whatever the science is, it works.",
    'testi-4-txt':"At 54 I had accepted that my hips would always ache and my energy would always be low. Yogi Khasha showed me that wasn't aging — it was something I could change. Four months in, the ache is gone. Not exaggerating.",
    'testi-5-txt':"I came for the posture benefits and stayed for everything else. My sleep improved, digestion regulated, mood lifted. There's something genuinely different about this approach — it works at a level other movement practices simply don't reach.",
    'testi-6-txt':"My doctor asked what I'd changed because my blood pressure and resting heart rate had both dropped. Their exact words: 'Keep doing whatever that is.' I fully intend to.",
    'testi-7-txt':"Fifteen minutes every morning. That's all it takes. I used to need two coffees just to feel human. Now I do my morning sequence and I'm genuinely energized for the whole day. At 58.",
    'testi-8-txt':"The spine work alone was worth everything. I had resigned myself to living with lower back pain as a permanent companion. Six weeks into this program, it was completely gone. I am never stopping.",
    'testi-9-txt':"I've tried yoga, gym classes, and personal training. Nothing touched what this practice does. You feel younger. Not metaphorically. Actually, genuinely, physically younger. I'll be doing this for life.",
    'testi-10-txt':"I was 67 and moving like I was 80. Now I'm 67 and moving like I'm 50. Yogi Khasha didn't just change how I exercise — they gave me my body back.",
    'prog-days-label':'Days Practiced',
    'btn-log-today':"+ Log Today's Practice",
    'already-logged-txt':'✓ Already logged today',
    'all-done-title':'You Have Mastered the Ancient Five',
    'all-done-sub':'365 days of unbroken practice. You carry the ritual in every cell of your body. This is who you are now — and it cannot be taken from you.',
    'badge-earned':'Earned',
    'badge-just-one-more':'Just 1 more day to unlock',
    'badge-more-days-to':'more days to unlock',
    'ny-eyebrow':'Members Exclusive',
    'ny-hero-sub':'A dedicated practice space where movement is experienced in its most authentic, liberated form. Professionally produced, artistically guided, and offered as an independent membership for the practitioner ready to explore a deeper dimension of embodied awareness.',
    'ny-badge-active':'Premium Access Active',
    'ny-why-1-title':'Artistic &amp; Professional',
    'ny-why-1-body':'Every session is produced by certified yoga instructors under the principles of artistic nudity — a globally recognized wellness discipline focused entirely on movement, form, and body reverence. Not explicit content. Pure practice.',
    'ny-why-2-title':'A Deeper Practice',
    'ny-why-2-body':'Without the distraction of clothing, every posture is felt at its fullest depth — skin, breath, and gravity working together to produce a quality of presence and body intelligence that clothed practice rarely reaches.',
    'ny-why-3-title':'Body Liberation',
    'ny-why-3-body':'Practiced across cultures for centuries, naked yoga dissolves the layers of self-judgment that clothed practice rarely touches — returning you to a natural, unconditional relationship with your own body.',
    'ny-why-4-title':'An Independent Membership',
    'ny-why-4-body':'This section is not included in any standard Yogi Khasha plan. It is a completely separate annual membership — intentional, exclusive, and reserved for the practitioner who is consciously ready.',
    'ny-gate-title':'A Separate, Dedicated Membership',
    'ny-gate-btn':'Get Annual Access — €120/year',
    'ny-gate-hint':'Already a member?',
    'ny-modal-title':'Naked Yoga — Annual Membership',
    'ny-modal-plan-name':'Annual Membership',
    'ny-modal-plan-trial':'Naked Yoga included · 30-day guarantee',
    'ny-modal-btn':'Get Annual Access',
    'ny-modal-tiny':'Annual commitment. 30-day money-back guarantee. No free trial.',
    'ny-sec-label':'Naked Yoga Classes',
    'nav-back':'Back'
  },
  de: {
    'nav-practice':'Praxis','nav-courses':'Kurse','nav-join-free':'Kostenlos starten',
    'nav-login':'Anmelden','nav-logout':'Abmelden','nav-badges':'Abzeichen',
    'nav-support':'Support','nav-about':'Über uns','nav-privacy':'Datenschutz','nav-terms':'Nutzungsbedingungen',
    'hero-sub':'Fordere Deinen Zeitlosen Körper Zurück',
    'hero-badge':'Vertraut von über <strong>3.400</strong> Praktizierenden in 40+ Ländern',
    'hero-btn':'Kostenlos starten',
    'stat-members':'Weltweite Mitglieder','stat-countries':'Länder',
    'stat-rating':'Durchschnittsbewertung','stat-years':'Jahre Erfahrung',
    'why-title-1':'Nur 15 Minuten am Tag','why-sub-1':'Alles, was du brauchst, um das Altern umzukehren',
    'why-title-2':'Komplett von zu Hause','why-sub-2':'Kein Studio, kein Pendelweg, kein Zeitplan',
    'why-title-3':'Kein Equipment nötig','why-sub-3':'Nur dein Körper und 21 Jahre Erfahrung',
    'section4-title':'Minuten am Tag. Jahre zurückgewonnen.',
    'section4-body':'Greife von jedem Gerät auf deine gesamte Bibliothek geführter Einheiten zu — von 10-minütigen Morgenritualen bis hin zu vollständigen einstündigen Praktiken. Jede Einheit basiert auf denselben fünf Kernbewegungen, die direkt auf deine Wirbelsäule, deine Energiezentren und dein Hormonsystem wirken. Das Ergebnis: Du beginnst dich jünger zu bewegen, zu fühlen und auszusehen — auf natürliche Weise, ohne Medikamente, ohne Chirurgie und ohne das Haus zu verlassen.',
    'testi-heading':'Echte Ergebnisse von echten Menschen',
    'testi-sub':'Über <strong style="color:#1e3a8a">3.400 Mitglieder</strong> in mehr als 40 Ländern haben ihre Jugend zurückerobert.',
    'cta-community':'Schließe dich <strong style="color:#1e3a8a">über 3.400 Mitgliedern</strong> an, die bereits jünger leben.',
    'cta-btn':'Kostenlos starten — Keine Kreditkarte nötig',
    'cta-sub':'Kostenlos starten &nbsp;·&nbsp; 15 Minuten am Tag &nbsp;·&nbsp; Jederzeit kündbar',
    'modal-title':'Werde Teil von über 3.400 Mitgliedern',
    'modal-stars':'★★★★★ &ensp;Kostenlos starten — keine Kreditkarte nötig',
    'modal-b1-title':'Altes Wissen. Moderne Ergebnisse.',
    'modal-b1-sub':'Fünf tägliche Bewegungen, die die natürlichen Verjüngungsmechanismen deines Körpers reaktivieren',
    'modal-b2-title':'Körperliches Altern umkehren',
    'modal-b2-sub':'Energie, Mobilität und Vitalität wiederherstellen — ab der ersten Einheit',
    'modal-b3-title':'Überall und jederzeit üben',
    'modal-b3-sub':'Deine vollständige Anti-Aging-Bewegungsbibliothek auf jedem Gerät',
    'modal-fname':'Vorname','modal-fname-ph':'Vorname',
    'modal-email':'E-Mail','modal-email-ph':'E-Mail-Adresse',
    'modal-signup-btn':'Konto erstellen',
    'modal-legal':'Mit deiner Anmeldung stimmst du unseren zu','modal-have-account':'Bereits ein Konto?',
    'page-practice':'Praxis',
    'page-practice-sub':'Alte Bewegungspraktiken zur Wiederherstellung von Vitalität, Mobilität und natürlicher Jugendlichkeit.',
    'sec-classes':'Klassen','sec-series':'Serien','btn-viewall':'Alle anzeigen',
    'label-members-only':'Nur Mitglieder','label-free':'KOSTENLOS',
    'modal-unlock-title':'Vollen Zugang freischalten','modal-unlock-sub':'Alle Klassen, alle Serien — unbegrenzt.',
    'plan-annual':'Jährlich','plan-annual-sub':'Weniger als €8 / Monat',
    'plan-best-value':'Bestes Angebot','plan-annual-cycle':'pro Jahr',
    'plan-monthly':'Monatlich','plan-monthly-sub':'Jederzeit kündbar','plan-monthly-cycle':'pro Monat',
    'btn-get-access':'Vollen Zugang erhalten','modal-tiny':'Sofortiger Zugang. Jederzeit kündbar.',
    'page-courses':'Kurse',
    'page-courses-sub':'Intensive Programme auf Basis alter Bewegungswissenschaft — entwickelt, um deinen Körper zu seiner vitalsten Form zurückzubringen.',
    'btn-view-course':'Kurs ansehen',
    'pay-subscribe':'Yogi Khasha abonnieren','pay-one-time':'Einmaliger Kauf',
    'pay-instant':'Sofortiger Zugang · Kein Abonnement erforderlich',
    'pay-lifetime':'Lebenslanger Zugang · Kein Abonnement erforderlich',
    'pay-billed-yearly':'Jährliche Abrechnung · Jederzeit kündbar',
    'pay-billed-monthly':'Monatliche Abrechnung · Jederzeit kündbar',
    'pay-subtotal':'Zwischensumme','pay-after-trial':'Gesamtbetrag nach Test','pay-due-today':'Heute fällig',
    'pay-promo-ph':'Aktionscode hinzufügen','pay-apply':'Anwenden',
    'pay-express':'Expressbestellung','pay-or-card':'oder mit Karte bezahlen',
    'pay-email':'E-Mail','pay-payment-details':'Zahlungsdetails',
    'pay-card-number':'Kartennummer','pay-expiry':'Ablaufdatum','pay-cvc':'CVC',
    'pay-cardholder':'Karteninhaber','pay-country':'Land',
    'pay-save':'Zahlungsdaten für zukünftige Käufe speichern',
    'pay-btn-subscribe':'Jetzt abonnieren',
    'page-badges':'Abzeichen','page-badges-sub':'Jeder Meilenstein in deinen Körper eingraviert.',
    'badge-tier-initiate':'Anfänger','badge-tier-practitioner':'Praktizierender',
    'badge-tier-warrior':'Krieger','badge-tier-master':'Meister',
    'badge-days':'Tage','badge-locked':'Gesperrt',
    'footer-copy':'© 2026 Yogi Khasha · Alle Inhalte © Multi Yoga Style · Alle Rechte vorbehalten.',
    'footer-support':'Support','footer-privacy':'Datenschutzrichtlinie','footer-terms':'Nutzungsbedingungen',
    'btn-buy-now':'Jetzt kaufen','lbl-instant-access':'Sofortiger Zugang · Kein Abonnement',
    'lbl-course-content':'Kursinhalt','lbl-online-course':'Online-Kurs',
    'lbl-by':'Von',
    'section-h1-main':'Die uralte Praxis mit 5 täglichen Bewegungen, die die Uhr Ihres Körpers zurückdreht — mehr Energie, weniger Schmerzen und eine Wirbelsäule, die sich 20 Jahre jünger anfühlt.',
    'about-body':"Mit über 21 Jahren Lehrerfahrung und Tausenden verwandelter Leben hat Yogi Khasha zwei Jahrzehnte damit verbracht, die alten Bewegungsabfolgen zu meistern, die die moderne Wissenschaft heute bestätigt: Fünf spezifische Bewegungen, täglich ausgeführt, die die natürlichen Verjüngungsmechanismen deines Körpers reaktivieren. Das ist keine Übung — es ist das kraftvollste Anti-Aging-Ritual, das dein Körper durchzuführen bestimmt war.",
    'quote-text':"''Ich hätte wirklich nicht geglaubt, dass eine tägliche Bewegungspraxis so viel verändern kann. Innerhalb von drei Wochen hatte ich die Steifheit verloren, die ich jahrelang mit mir getragen hatte, meine Energie war zurück, und die Leute fragten mich ständig, ob ich etwas geändert hätte. Die Antwort war genau das — fünf Bewegungen, jeden Morgen. Das war alles.''",
    'footer-tagline':'Mit ♥ auf dem Planeten Erde gemacht.',
    'testi-1-txt':'Ich habe jahrelang geglaubt, Steifheit und Erschöpfung seien einfach Teil des Älterwerdens. Nach sechs Wochen mit Yogi Khasha sind meine Morgen völlig anders — ich wache mit echter Energie auf, mein Rücken schmerzt nicht mehr, und ich bewege mich wie früher mit Mitte vierzig. Ich bin 61.',
    'testi-2-txt':"Ich hätte die Veränderung fast nicht bemerkt, bis meine Tochter sagte: 'Mama, du gehst anders.' Aufrechter. Selbstsicherer. Drei Monate später habe ich keinen einzigen Tag ausgelassen.",
    'testi-3-txt':'Ich war skeptisch — Energiezentren und alte Rituale sind normalerweise nicht meine Sprache. Aber die Ergebnisse sind unbestreitbar. Weniger Schmerzen, mehr Energie, besserer Schlaf und eine Haltung, die mein Physiotherapeut sogar kommentiert hat.',
    'testi-4-txt':'Mit 54 hatte ich akzeptiert, dass meine Hüften immer schmerzen und meine Energie immer niedrig sein würde. Yogi Khasha hat mir gezeigt, dass das kein Altern war — es war etwas, das ich ändern konnte. Vier Monate später sind die Schmerzen weg. Kein Witz.',
    'testi-5-txt':"Ich kam wegen der Haltungsverbesserungen und blieb wegen allem anderen. Mein Schlaf verbesserte sich, die Verdauung regulierte sich, die Stimmung hob sich. Dieser Ansatz ist wirklich anders.",
    'testi-6-txt':"Mein Arzt fragte, was ich geändert hätte, weil mein Blutdruck und meine Ruheherzfrequenz beide gesunken waren. Seine genauen Worte: 'Mach weiter, was auch immer das ist.' Das habe ich fest vor.",
    'testi-7-txt':'Fünfzehn Minuten jeden Morgen. Wirklich, das ist alles. Früher brauchte ich zwei Kaffees, um mich menschlich zu fühlen. Jetzt mache ich meine Morgensequenz und bin den ganzen Tag wirklich energiegeladen. Mit 58.',
    'testi-8-txt':'Die Arbeit an der Wirbelsäule allein war alles wert. Ich hatte mich damit abgefunden, mit Rückenschmerzen zu leben. Sechs Wochen in diesem Programm waren sie vollständig verschwunden. Ich werde nie aufhören.',
    'testi-9-txt':"Ich habe Yoga, Fitnesskurse und Personal Training ausprobiert. Nichts hat das berührt, was diese Praxis bewirkt. Man fühlt sich jünger. Nicht im übertragenen Sinne. Wirklich, körperlich jünger.",
    'testi-10-txt':'Ich war 67 und bewegte mich wie 80. Jetzt bin ich 67 und bewege mich wie 50. Yogi Khasha hat nicht nur meine Bewegung verändert — sie haben mir meinen Körper zurückgegeben.',
    'prog-days-label':'Geübte Tage',
    'btn-log-today':'+ Heutige Praxis eintragen',
    'already-logged-txt':'✓ Heute bereits eingetragen',
    'all-done-title':'Du hast die Alten Fünf gemeistert',
    'all-done-sub':'365 Tage ununterbrochener Praxis. Du trägst das Ritual in jeder Zelle deines Körpers. Das ist jetzt, wer du bist — und es kann dir nicht genommen werden.',
    'badge-earned':'Verdient',
    'badge-just-one-more':'Nur noch 1 Tag bis zum Entsperren von',
    'badge-more-days-to':'weitere Tage bis zum Entsperren von',
    'ny-eyebrow':'Exklusiv für Mitglieder',
    'ny-hero-sub':'Ein dedizierter Übungsraum, in dem Bewegung in ihrer authentischsten, befreitsten Form erlebt wird. Professionell produziert, künstlerisch geleitet und als unabhängige Mitgliedschaft angeboten.',
    'ny-badge-active':'Premium-Zugang aktiv',
    'ny-why-1-title':'Künstlerisch &amp; Professionell',
    'ny-why-1-body':'Jede Einheit wird von zertifizierten Yoga-Lehrern unter den Prinzipien der künstlerischen Nacktheit produziert — eine weltweit anerkannte Wellness-Disziplin, die sich auf Bewegung, Form und Körperverehrung konzentriert. Kein expliziter Inhalt. Reine Praxis.',
    'ny-why-2-title':'Eine tiefere Praxis',
    'ny-why-2-body':'Ohne die Ablenkung durch Kleidung wird jede Haltung in ihrer vollen Tiefe gespürt — Haut, Atem und Schwerkraft erzeugen gemeinsam eine Qualität der Präsenz und Körperintelligenz, die bekleidete Praxis selten erreicht.',
    'ny-why-3-title':'Körperbefreiung',
    'ny-why-3-body':'Seit Jahrhunderten in verschiedenen Kulturen praktiziert, löst Naked Yoga die Schichten des Selbsturteils auf — und gibt dir eine natürliche, bedingungslose Beziehung zu deinem eigenen Körper zurück.',
    'ny-why-4-title':'Eine unabhängige Mitgliedschaft',
    'ny-why-4-body':'Dieser Bereich ist in keinem Standard-Yogi-Khasha-Plan enthalten. Es handelt sich um eine völlig separate Jahresmitgliedschaft — bewusst, exklusiv und vorbehalten für den Praktizierenden, der bereit ist.',
    'ny-gate-title':'Eine separate, dedizierte Mitgliedschaft',
    'ny-gate-btn':'Jahreszugang erhalten — €120/Jahr',
    'ny-gate-hint':'Bereits Mitglied?',
    'ny-modal-title':'Naked Yoga — Jahresmitgliedschaft',
    'ny-modal-plan-name':'Jahresmitgliedschaft',
    'ny-modal-plan-trial':'Naked Yoga inklusive · 30-Tage-Garantie',
    'ny-modal-btn':'Jahreszugang erhalten',
    'ny-modal-tiny':'Jahresverpflichtung. 30-Tage-Geldback-Garantie. Keine kostenlose Testphase.',
    'ny-sec-label':'Naked Yoga Klassen',
    'nav-back':'Zurück'
  },
  es: {
    'nav-practice':'Práctica','nav-courses':'Cursos','nav-join-free':'Empieza Gratis',
    'nav-login':'Iniciar Sesión','nav-logout':'Cerrar Sesión','nav-badges':'Insignias',
    'nav-support':'Soporte','nav-about':'Acerca de','nav-privacy':'Política de Privacidad','nav-terms':'Términos de Servicio',
    'hero-sub':'Reclama Tu Cuerpo Sin Edad',
    'hero-badge':'De confianza para más de <strong>3.400</strong> practicantes en más de 40 países',
    'hero-btn':'Empieza Gratis Hoy',
    'stat-members':'Miembros en el Mundo','stat-countries':'Países',
    'stat-rating':'Valoración Media','stat-years':'Años de Enseñanza',
    'why-title-1':'Solo 15 minutos al día','why-sub-1':'Todo lo que necesitas para revertir el envejecimiento',
    'why-title-2':'Completamente desde casa','why-sub-2':'Sin gimnasio, sin desplazamientos, sin horarios',
    'why-title-3':'Sin equipamiento necesario','why-sub-3':'Solo tu cuerpo y 21 años de guía',
    'section4-title':'Minutos al Día. Años Devueltos.',
    'section4-body':'Accede a tu biblioteca completa de sesiones guiadas desde cualquier dispositivo — desde rituales matutinos de 10 minutos hasta prácticas completas de una hora. Cada sesión está construida alrededor de los mismos cinco movimientos centrales que hablan directamente a tu columna, tus centros de energía y tu sistema hormonal. El resultado: empiezas a moverte, sentirte y verte más joven — de forma natural, sin medicamentos, sin cirugía y sin salir de casa.',
    'testi-heading':'Resultados Reales de Personas Reales',
    'testi-sub':'Más de <strong style="color:#1e3a8a">3.400 miembros</strong> en más de 40 países han recuperado su juventud.',
    'cta-community':'Únete a <strong style="color:#1e3a8a">más de 3.400 miembros</strong> que ya están viviendo más jóvenes.',
    'cta-btn':'Empieza Gratis — Sin Tarjeta de Crédito',
    'cta-sub':'Gratis para empezar &nbsp;·&nbsp; 15 minutos al día &nbsp;·&nbsp; Cancela cuando quieras',
    'modal-title':'Únete a Más de 3.400 Miembros',
    'modal-stars':'★★★★★ &ensp;Empieza gratis hoy — sin tarjeta de crédito',
    'modal-b1-title':'Sabiduría Ancestral. Resultados Modernos.',
    'modal-b1-sub':'Cinco movimientos diarios que reactivan los mecanismos de juventud natural de tu cuerpo',
    'modal-b2-title':'Revertir el Envejecimiento Físico',
    'modal-b2-sub':'Restaura energía, movilidad y vitalidad — desde la primera sesión',
    'modal-b3-title':'Practica en Cualquier Lugar',
    'modal-b3-sub':'Tu biblioteca completa de movimiento anti-envejecimiento, en cualquier dispositivo',
    'modal-fname':'Nombre','modal-fname-ph':'nombre',
    'modal-email':'Correo electrónico','modal-email-ph':'dirección de correo',
    'modal-signup-btn':'Crear Cuenta',
    'modal-legal':'Al unirte aceptas nuestros','modal-have-account':'¿Ya tienes una cuenta?',
    'page-practice':'Práctica',
    'page-practice-sub':'Prácticas de movimiento ancestral para restaurar la vitalidad, la movilidad y la juventud natural de tu cuerpo.',
    'sec-classes':'Clases','sec-series':'Series','btn-viewall':'Ver todo',
    'label-members-only':'Solo Miembros','label-free':'GRATIS',
    'modal-unlock-title':'Desbloquea el Acceso Completo','modal-unlock-sub':'Todas las clases, todas las series — ilimitado.',
    'plan-annual':'Anual','plan-annual-sub':'Menos de €8 / mes',
    'plan-best-value':'Mejor Precio','plan-annual-cycle':'por año',
    'plan-monthly':'Mensual','plan-monthly-sub':'Cancela cuando quieras','plan-monthly-cycle':'por mes',
    'btn-get-access':'Obtener Acceso Completo','modal-tiny':'Acceso inmediato. Cancela cuando quieras.',
    'page-courses':'Cursos',
    'page-courses-sub':'Programas intensivos basados en ciencia del movimiento ancestral — diseñados para devolver a tu cuerpo su estado más vital.',
    'btn-view-course':'Ver Curso',
    'pay-subscribe':'Suscríbete a Yogi Khasha','pay-one-time':'Compra Única',
    'pay-instant':'Acceso inmediato · Sin suscripción necesaria',
    'pay-lifetime':'Acceso de por vida · Sin suscripción necesaria',
    'pay-billed-yearly':'Facturación anual · Cancela cuando quieras',
    'pay-billed-monthly':'Facturación mensual · Cancela cuando quieras',
    'pay-subtotal':'Subtotal','pay-after-trial':'Total tras el periodo de prueba','pay-due-today':'Total hoy',
    'pay-promo-ph':'Añadir código promocional','pay-apply':'Aplicar',
    'pay-express':'Pago Rápido','pay-or-card':'o paga con tarjeta',
    'pay-email':'Correo electrónico','pay-payment-details':'Detalles de Pago',
    'pay-card-number':'Número de Tarjeta','pay-expiry':'Caducidad','pay-cvc':'CVC',
    'pay-cardholder':'Nombre del Titular','pay-country':'País',
    'pay-save':'Guardar datos de pago para futuras compras',
    'pay-btn-subscribe':'Suscribirse ahora',
    'page-badges':'Insignias','page-badges-sub':'Cada hito grabado en tu cuerpo.',
    'badge-tier-initiate':'Iniciado','badge-tier-practitioner':'Practicante',
    'badge-tier-warrior':'Guerrero','badge-tier-master':'Maestro',
    'badge-days':'días','badge-locked':'Bloqueado',
    'footer-copy':'© 2026 Yogi Khasha · Todo el contenido © Multi Yoga Style · Todos los derechos reservados.',
    'footer-support':'Soporte','footer-privacy':'Política de Privacidad','footer-terms':'Términos de Servicio',
    'btn-buy-now':'Comprar ahora','lbl-instant-access':'Acceso inmediato · Sin suscripción',
    'lbl-course-content':'Contenido del Curso','lbl-online-course':'Curso Online',
    'lbl-by':'Por',
    'section-h1-main':'La Práctica Diaria de 5 Movimientos Ancestrales Que Revierte el Reloj de Tu Cuerpo — Más Energía, Menos Dolor y una Columna Que Se Siente 20 Años Más Joven.',
    'about-body':'Con más de 21 años de experiencia docente y miles de vidas transformadas, Yogi Khasha ha dedicado dos décadas a dominar las secuencias de movimiento ancestrales que la ciencia moderna confirma: cinco movimientos específicos, practicados diariamente, que reactivan los mecanismos naturales de juventud de tu cuerpo. Esto no es ejercicio — es el ritual anti-envejecimiento más poderoso que tu cuerpo fue diseñado para realizar.',
    'quote-text':"''Sinceramente no creía que una práctica diaria de movimiento pudiera cambiar tanto. En tres semanas había perdido la rigidez que había cargado durante años, mi energía había vuelto, y la gente seguía preguntándome si había hecho algo diferente. La respuesta era simplemente esta — cinco movimientos, cada mañana. Eso es todo.''",
    'footer-tagline':'Hecho con ♥ en el planeta tierra.',
    'testi-1-txt':'Pasé años creyendo que la rigidez y la poca energía eran simplemente parte del envejecimiento. Después de seis semanas con Yogi Khasha, mis mañanas son completamente diferentes — me despierto con energía real, mi espalda no duele, y me muevo como lo hacía a los cuarenta. Tengo 61 años.',
    'testi-2-txt':"Casi no noté el cambio hasta que mi hija dijo: 'Mamá, caminas diferente.' Más erguida. Más segura. Tres meses después, no he faltado un solo día.",
    'testi-3-txt':'Era escéptico — los centros de energía y los rituales ancestrales no suelen ser mi lenguaje. Pero los resultados son innegables. Menos dolor, más energía, mejor sueño y una postura que mi fisioterapeuta comentó.',
    'testi-4-txt':'A los 54 había aceptado que mis caderas siempre dolerían y mi energía siempre sería baja. Yogi Khasha me mostró que eso no era envejecer — era algo que podía cambiar. Cuatro meses después, el dolor desapareció. Sin exagerar.',
    'testi-5-txt':"Vine por los beneficios posturales y me quedé por todo lo demás. Mi sueño mejoró, la digestión se reguló, el ánimo subió. Hay algo genuinamente diferente en este enfoque.",
    'testi-6-txt':"Mi médico preguntó qué había cambiado porque mi presión arterial y mi frecuencia cardíaca en reposo habían bajado. Sus palabras exactas: 'Sigue haciendo lo que sea que estás haciendo.' Así lo haré.",
    'testi-7-txt':'Quince minutos cada mañana. De verdad, eso es todo. Antes necesitaba dos cafés para sentirme humano. Ahora hago mi secuencia matutina y tengo energía genuina todo el día. A los 58.',
    'testi-8-txt':'El trabajo de columna solo ya valió todo. Me había resignado a vivir con dolor lumbar. Seis semanas en este programa, había desaparecido por completo. Nunca voy a parar.',
    'testi-9-txt':'He probado yoga, clases de gimnasio y entrenamiento personal. Nada tocó lo que hace esta práctica. Te sientes más joven. No metafóricamente. Real, genuina y físicamente más joven.',
    'testi-10-txt':'Tenía 67 años y me movía como si tuviera 80. Ahora tengo 67 y me muevo como si tuviera 50. Yogi Khasha no solo cambió cómo hago ejercicio — me devolvieron mi cuerpo.',
    'prog-days-label':'Días Practicados',
    'btn-log-today':'+ Registrar práctica de hoy',
    'already-logged-txt':'✓ Ya registrado hoy',
    'all-done-title':'Has Dominado los Cinco Ancestrales',
    'all-done-sub':'365 días de práctica ininterrumpida. Llevas el ritual en cada célula de tu cuerpo. Esto es quien eres ahora — y no te puede ser arrebatado.',
    'badge-earned':'Ganado',
    'badge-just-one-more':'Solo 1 día más para desbloquear',
    'badge-more-days-to':'días más para desbloquear',
    'ny-eyebrow':'Exclusivo para Miembros',
    'ny-hero-sub':'Un espacio de práctica dedicado donde el movimiento se experimenta en su forma más auténtica y liberada. Producido profesionalmente, guiado artísticamente y ofrecido como membresía independiente para el practicante listo para explorar una dimensión más profunda de conciencia corporal.',
    'ny-badge-active':'Acceso Premium Activo',
    'ny-why-1-title':'Artístico &amp; Profesional',
    'ny-why-1-body':'Cada sesión es producida por instructores de yoga certificados bajo los principios de la desnudez artística — una disciplina de bienestar reconocida mundialmente enfocada en el movimiento, la forma y la reverencia corporal. No es contenido explícito. Práctica pura.',
    'ny-why-2-title':'Una Práctica Más Profunda',
    'ny-why-2-body':'Sin la distracción de la ropa, cada postura se siente en su máxima profundidad — piel, respiración y gravedad trabajando juntos para producir una calidad de presencia e inteligencia corporal que la práctica vestida raramente alcanza.',
    'ny-why-3-title':'Liberación Corporal',
    'ny-why-3-body':'Practicado en culturas durante siglos, el yoga desnudo disuelve las capas de autojuicio — devolviéndote una relación natural e incondicional con tu propio cuerpo y su sabiduría.',
    'ny-why-4-title':'Una Membresía Independiente',
    'ny-why-4-body':'Esta sección no está incluida en ningún plan estándar de Yogi Khasha. Es una membresía anual completamente separada — intencional, exclusiva y reservada para el practicante que está conscientemente listo.',
    'ny-gate-title':'Una Membresía Separada y Dedicada',
    'ny-gate-btn':'Obtener Acceso Anual — €120/año',
    'ny-gate-hint':'¿Ya eres miembro?',
    'ny-modal-title':'Yoga Desnudo — Membresía Anual',
    'ny-modal-plan-name':'Membresía Anual',
    'ny-modal-plan-trial':'Naked Yoga incluido · Garantía de 30 días',
    'ny-modal-btn':'Obtener Acceso Anual',
    'ny-modal-tiny':'Compromiso anual. Garantía de devolución de 30 días. Sin periodo de prueba gratuito.',
    'ny-sec-label':'Clases de Yoga Desnudo',
    'nav-back':'Volver'
  }
};

function getLang(){ return localStorage.getItem('yk_lang')||'en'; }
function setLang(l){ localStorage.setItem('yk_lang',l); applyLang(); }
function applyLang(){
  const t=TRANSLATIONS[getLang()]||TRANSLATIONS.en;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const k=el.getAttribute('data-i18n');
    if(t[k]!==undefined) el.innerHTML=t[k];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el=>{
    const k=el.getAttribute('data-i18n-ph');
    if(t[k]!==undefined) el.placeholder=t[k];
  });
  document.querySelectorAll('.lang-select').forEach(sel=>{ sel.value=getLang(); });
}
document.addEventListener('DOMContentLoaded',applyLang);
